# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myscreen1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from base_datos import conn


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(689, 536)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.proveeCombustible = QtWidgets.QLineEdit(self.centralwidget)
        self.proveeCombustible.setGeometry(QtCore.QRect(10, 50, 351, 23))
        self.proveeCombustible.setObjectName("proveeCombustible")
        self.numGlns = QtWidgets.QLineEdit(self.centralwidget)
        self.numGlns.setGeometry(QtCore.QRect(250, 90, 113, 23))
        self.numGlns.setText("")
        self.numGlns.setObjectName("numGlns")
        self.guardar = QtWidgets.QPushButton(self.centralwidget)
        self.guardar.setGeometry(QtCore.QRect(90, 168, 211, 21))
        self.guardar.setObjectName("guardar")
        self.actualizar = QtWidgets.QPushButton(self.centralwidget)
        self.actualizar.setGeometry(QtCore.QRect(90, 220, 211, 21))
        self.actualizar.setObjectName("actualizar")
        self.listaIngresos = QtWidgets.QTableWidget(self.centralwidget)
        self.listaIngresos.setGeometry(QtCore.QRect(420, 70, 256, 192))
        self.listaIngresos.setObjectName("listaIngresos")
        self.listaIngresos.setColumnCount(0)
        self.listaIngresos.setRowCount(0)
        self.label_nombreProveedor = QtWidgets.QLabel(self.centralwidget)
        self.label_nombreProveedor.setGeometry(QtCore.QRect(10, 20, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_nombreProveedor.setFont(font)
        self.label_nombreProveedor.setObjectName("label_nombreProveedor")
        self.label_cantGlns = QtWidgets.QLabel(self.centralwidget)
        self.label_cantGlns.setGeometry(QtCore.QRect(170, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_cantGlns.setFont(font)
        self.label_cantGlns.setObjectName("label_cantGlns")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 689, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
    # guardar
        self.crear_base()
        self.obtener_informacion()
        self.guardar.clicked.connect(self.guardar_informacion)
        self.actualizar.clicked.connect(self.obtener_informacion)
    #
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.guardar.setText(_translate("MainWindow", "Guardar"))
        self.actualizar.setText(_translate("MainWindow", "Actualizar"))
        self.label_nombreProveedor.setText(_translate("MainWindow", "Proveedor"))
        self.label_cantGlns.setText(_translate("MainWindow", "Galones"))

    def crear_base(self):
        cursor = conn.cursor()
        cadena_sql = 'CREATE TABLE Proveedores (proveeCombustible TEXT, numGlns INTEGER, costoGln INTEGER)'
        try:
            cursor.execute(cadena_sql)
        except:
            pass
        cursor.close()

    def guardar_informacion(self):
        cursor = conn.cursor()
        proveeCombustible = str(self.proveeCombustible.text())
        numGlns = int(self.numGlns.text())
        costo = numGlns*3
        # Usar parámetros en la consulta SQL
        cadena_sql = "INSERT INTO Proveedores (proveeCombustible, numGlns, costoGln) VALUES (?, ?, ?);"
        #(proveeCombustible, numGlns, costo)
        # ejecutar el SQL
        cursor.execute(cadena_sql, (proveeCombustible, numGlns, costo))
        # confirmar los cambios
        conn.commit()
        cursor.close()

    def obtener_informacion(self):
        cursor = conn.cursor()
        cadena_consulta_sql = "SELECT * from Proveedores"
        cursor.execute(cadena_consulta_sql)
        informacion = cursor.fetchall()
        database_table_column_count = 3
        self.listaIngresos.setColumnCount(database_table_column_count)
        numero_filas = len(informacion)
        self.listaIngresos.setRowCount(numero_filas)
        for j in range(numero_filas):
            valor = informacion[j]
            for i in range(0, len(valor)):
                elemento = valor[i]
                elemento = str(elemento)
                nuevo_registro = QtWidgets.QTableWidgetItem(elemento)
                self.listaIngresos.setItem(j, i, nuevo_registro)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
